"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useState } from "react";
import { doc,getDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { Product } from "@/lib/types";
import { STORE } from "@/lib/config";
export default function ProductPage(){const params=useParams<{id:string}>();const[p,setP]=useState<Product|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{if(!params.id)return;getDoc(doc(db,"products",params.id)).then(s=>s.exists()?setP({id:s.id,...(s.data() as Omit<Product,"id">)}):setP(null)).finally(()=>setLoading(false))},[params.id]);if(loading)return <main className="mx-auto max-w-6xl px-4 py-20">Memuat produk...</main>;if(!p)return <main className="mx-auto max-w-6xl px-4 py-20">Produk tidak ditemukan.</main>;const msg=`Halo, saya ingin memesan ${p.name}. Harga: Rp${Number(p.price).toLocaleString("id-ID")}.`;return <main className="mx-auto max-w-6xl px-4 py-12"><Link href="/katalog" className="text-sm text-neutral-500">← Kembali ke katalog</Link><div className="mt-6 grid gap-10 md:grid-cols-2"><div className="aspect-[4/5] overflow-hidden rounded-3xl bg-neutral-100"><img src={p.images?.[0]} alt={p.name} className="h-full w-full object-cover"/></div><div><p className="text-sm uppercase tracking-wider text-neutral-500">{p.category}</p><h1 className="mt-2 text-4xl font-black">{p.name}</h1><p className="mt-4 text-2xl font-bold">Rp{Number(p.price).toLocaleString("id-ID")}</p><p className="mt-6 leading-7 text-neutral-600">{p.description}</p><p className="mt-8 font-semibold">Ukuran</p><div className="mt-3 flex flex-wrap gap-2">{p.sizes?.map(s=><span key={s} className="rounded-lg border px-4 py-2 text-sm">{s}</span>)}</div><p className="mt-6 font-semibold">Warna</p><div className="mt-3 flex flex-wrap gap-2">{p.colors?.map(x=><span key={x} className="rounded-lg border px-4 py-2 text-sm">{x}</span>)}</div><a href={`https://wa.me/${STORE.whatsapp}?text=${encodeURIComponent(msg)}`} target="_blank" rel="noreferrer" className="mt-9 block rounded-2xl bg-black px-6 py-4 text-center font-bold text-white">Pesan via WhatsApp</a></div></div></main>}
